### ISSUE TITLE
API enhancement (summary task)

### ISSUE THREAD

**Issue by pjuza** [integram/cleverbus#14]
Enhance CleverBus API to be more productive for common and often tasks when routes are implemented.
- [ ] [Simplify input route implementation](#15) 
- [ ] [Simplify output route implementation](#16) 
- [ ] [Clean and unify unit tests support](#9)
