### ISSUE TITLE
CleverBus in cluster (summary task)

### ISSUE THREAD

**Issue by pjuza** [integram/cleverbus#4]
Summary task to allow run CleverBus in cluster.
- [ ] [Throttling for cluster](#5)
- [ ] [Use cluster cache, e.g. Infinispan](#6)
- [ ] [Create healtCheck service for cluster](#7)
